### ISSUE TITLE
[BLOG] マークダウンでtableタグが表示されない

### ISSUE THREAD

**Issue by uraranbon** [dotstudio/dotstudio.github.io#17]
マークダウンで表を書いても反映されません。
以下、記入したソースを貼っておきます。

```
| 月日 | できごと |
|---||---|
| 2016.5 | dotstudio プレオープン |
| 2016.6  | β版リリース |
| 現在 | 順次拡大中 |
```
## tableについて

(github)[https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables]

> | Tables | Are | Cool |
> | --- | :-: | --: |
> | col 3 is | right-aligned | $1600 |
> | col 2 is | centered | $12 |
> | zebra stripes | are neat | $1 |
> 
> There must be at least 3 dashes separating each header cell.

**Comment by n0bisuke** [comment]
@GitHubUrara 

MDミスだよ！

```
| 月日 | できごと |
|---||---|
| 2016.5 | dotstudio プレオープン |
| 2016.6  | β版リリース |
| 現在 | 順次拡大中 |
```

↓

```
| 月日 | できごと |
|---|---|
| 2016.5 | dotstudio プレオープン |
| 2016.6  | β版リリース |
| 現在 | 順次拡大中 |
```
