### ISSUE TITLE
[BLOG] 画像が表示されない（アイキャッチ）

### ISSUE THREAD

**Issue by uraranbon** [dotstudio/dotstudio.github.io#18]
アイキャッチ画像を入れたいのですが入りませぬ。
私がアイキャッチだと思っているのは以下の場所です。
- ブログ記事一覧からでる画像（今は猫）
- 記事自体のアイキャッチ画像（これはそもそも出ない？）

下記じゃダメですかね・・・？
ご確認をお願いできれば幸いです。

`image = "members.jpg"`
（場所はあっている、はず）

**Comment by n0bisuke** [comment]
@GitHubUrara 

対応しました :)
 `image = "001/members.jpg"` みたいな感じでいれてみてください！
