### ISSUE TITLE
[BLOG] 画像が表示されない（記事内）

### ISSUE THREAD

**Issue by uraranbon** [dotstudio/dotstudio.github.io#19]
すみませんこれは入れ方が多分わかりません。
今は下記のように書いています。

`![members.jpg](members.jpg)`

参照：[github](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images)

```
Inline-style: 
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")

Reference-style: 
![alt text][logo]

[logo]: https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 2"
```

-> オンラインにない画像のやり方がみつから…ず…ほんとすいません…

**Comment by n0bisuke** [comment]
このやり方みたい http://step-learn.com/markdown/20141011-img-relative.html

**Comment by n0bisuke** [comment]
@GitHubUrara 

`themes/dotstudio/static/img/blog/001/grsakura.png`を使うときは

`![](/img/blog/001/grsakura.png)`で指定する感じで！
