### ISSUE TITLE
PayPal 値段自動取得

### ISSUE THREAD

**Issue by n0bisuke** [dotstudio/dotstudio.github.io#4]
とりあえず買える状態にはできたかも！

**Comment by n0bisuke** [comment]
@chachmaru  今、左下に購入ボタンがいるから試してみてほしい！

https://dotstud.io/projects/1.html

**Comment by n0bisuke** [comment]
ペイパルボタンの設置について
https://www.paypal.com/jp/cgi-bin/webscr?cmd=_pdn_xclick_techview_outside

**Comment by n0bisuke** [comment]
こっちだった https://www.paypal.com/jp/cgi-bin/webscr?cmd=_singleitem-intro-outside

**Comment by pprdoor** [comment]
現状：一つ一つ商品をpaypal側で登録
理想：値段をhtmlから取得して値段等を自動設定

**Comment by n0bisuke** [comment]
http://paypal.github.io/PayPal-node-SDK/

**Comment by n0bisuke** [comment]
https://www.paypal.com/jp/cgi-bin/customerprofileweb?cmd=_button-management
