### ISSUE TITLE
URL設計話

### ISSUE THREAD

**Issue by n0bisuke** [dotstudio/dotstudio.github.io#5]
https://dotstud.io/projects/1.html はわかりにくい&`.html`がださい

↓

https://dotstud.io/projects/01_nefry.html
だったり
https://dotstud.io/projects/nefrly/
とかにするのはどうだろう

**Comment by n0bisuke** [comment]
@chachmaru ping

**Comment by pprdoor** [comment]
各記事のURLは
projects/メイン商品-修飾1-修飾2
で統一する

https://dotstud.io/projects/nefry-connect-internet
https://dotstud.io/projects/grsakura-alchol-check

**Comment by n0bisuke** [comment]
@chachmaru 対応

 https://dotstud.io/projects/nefry-connect-internet/
